# 🐒 Clean MCP Tavily WebSearch - Portainer Stack
# Professional approach without embedded code

services:
  mcp-tavily:
    image: mcp-tavily-websearch:latest
    container_name: mcp-tavily-search
    restart: unless-stopped
    build:
      context: https://github.com/yourusername/WebsearchTool.git
      dockerfile: Dockerfile
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    ports:
      - "${EXTERNAL_PORT:-18000}:7000"
    networks: 
      - mcp-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:7000/mcp/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  mcp-network:
    driver: bridge
