version: "3.8"

services:
  mcp-tavily:
    build:
      context: .
    image: mcp-tavily:latest
    environment:
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      MCP_HOST: 0.0.0.0
      MCP_PORT: "8000"
    restart: unless-stopped
    networks:
      - mcpnet

  mcpo:
    image: ghcr.io/open-webui/mcpo:latest
    depends_on:
      - mcp-tavily
    command: >
      mcpo --host 0.0.0.0 --port 8001
           --server-type streamablehttp --
           http://mcp-tavily:8000/mcp
    restart: unless-stopped
    networks:
      - mcpnet

  nginx-auth:
    image: nginx:alpine
    depends_on:
      - mcpo
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    volumes:
      # Mount the entire directory. The Nginx entrypoint will find and process the .template file.
      - ./config/nginx:/etc/nginx/templates
    command: |
      /bin/sh -c '
        # Explicitly process the template using envsubst, now that the volume mount is correct.
        export AUTH_TOKEN && envsubst ''$$AUTH_TOKEN'' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf &&
        
        # Validate the generated config file before starting
        echo "--- Generated Nginx Config ---" &&
        cat /etc/nginx/conf.d/default.conf &&
        echo "------------------------------" &&
        nginx -t &&
        
        # Start Nginx
        echo "Starting Nginx..." &&
        nginx -g "daemon off;"
      '
    ports:
      - "18000:18000"
    restart: unless-stopped
    networks:
      - mcpnet

networks:
  mcpnet:
    driver: bridge