version: "3.8"

services:
  mcp-tavily:
    build: .
    image: mcp-tavily:latest
    container_name: mcp-tavily
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
    restart: unless-stopped
    networks: [mcpnet]
    # no external ports — internal only

  mcpo:
    image: ghcr.io/open-webui/mcpo:latest
    container_name: mcpo
    depends_on: [mcp-tavily]
    # Connect mcpo to our MCP server over Streamable HTTP
    command: >
      mcpo --host 0.0.0.0 --port 8001
           --server-type "streamablehttp" --
           http://mcp-tavily:8000/mcp
    restart: unless-stopped
    networks: [mcpnet]
    # internal only

  nginx-auth:
    image: nginx:alpine
    container_name: nginx-auth
    depends_on: [mcpo]
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}   # set in Portainer or .env (not committed)
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    ports:
      - "18000:18000"
    command: >
      /bin/sh -c '
        set -e
        echo "[nginx-auth] Verifying template path..."
        ls -l /etc/nginx/templates || true
        if [ ! -f /etc/nginx/templates/default.conf.template ]; then
          echo "[nginx-auth] ERROR: Template file missing or not a regular file."
          exit 1
        fi
        echo "[nginx-auth] Rendering config with envsubst..."
        envsubst "$$AUTH_TOKEN" < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf
        echo "[nginx-auth] Final config:"
        head -n 20 /etc/nginx/conf.d/default.conf || true
        exec nginx -g "daemon off;"
      '
    networks: [mcpnet]

networks:
  mcpnet:
    driver: bridge