version: "3.8"

services:
  mcp-tavily:
    build:
      context: .
    image: mcp-tavily:latest
    environment:
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      MCP_HOST: 0.0.0.0
      MCP_PORT: "8000"
    restart: unless-stopped
    networks:
      - mcpnet

  mcpo:
    image: ghcr.io/open-webui/mcpo:latest
    depends_on:
      - mcp-tavily
    command: >
      mcpo --host 0.0.0.0 --port 8001
           --server-type streamablehttp --
           http://mcp-tavily:8000/mcp
    restart: unless-stopped
    networks:
      - mcpnet

  gateway:
    image: nginx:alpine
    depends_on:
      - mcpo
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
    ports:
      - "18000:18000"
    restart: unless-stopped
    networks:
      - mcpnet

networks:
  mcpnet:
    driver: bridge
