version: "3.8"

services:
  mcpo:
    image: ghcr.io/open-webui/mcpo:latest
    environment:
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    command: >
      mcpo --host 0.0.0.0 --port 8001
           --server-type streamablehttp --
           https://mcp.tavily.com/mcp/?tavilyApiKey=${TAVILY_API_KEY}
    ports:
      - "18000:8001"
    restart: unless-stopped

# Note: Removed mcp-tavily service as we're now using Tavily's remote MCP server
# This dramatically simplifies our architecture and reduces maintenance overhead
