version: "3.8"

services:
  mcp-tavily:
    build: .
    image: mcp-tavily:latest
    container_name: mcp-tavily
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
    restart: unless-stopped
    networks: [mcpnet]

  # Recommended bridge to OpenWebUI: MCP -> OpenAPI via mcpo
  mcpo:
    image: ghcr.io/open-webui/mcpo:latest
    container_name: mcpo
    depends_on: [mcp-tavily]
    # Expose mcpo on 18001 and tell it our MCP server is streamable-http at http://mcp-tavily:8000/mcp
    command: >
      mcpo --host 0.0.0.0 --port 8001
           --server-type "streamablehttp" --
           http://mcp-tavily:8000/mcp
    ports:
      - "18000:8001"
    restart: unless-stopped
    networks: [mcpnet]

networks:
  mcpnet:
    driver: bridge