services:
  mcp-tavily:
    build: .
    container_name: mcp-tavily-search
    restart: unless-stopped
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    ports:
      - "${EXTERNAL_PORT:-18000}:7000"
    networks: 
      - mcp-network
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:7000/mcp/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mcp-network:
    driver: bridge