version: "3.8"

services:
  mcp-tavily:
    build:
      context: .
    image: mcp-tavily:latest
    environment:
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      MCP_HOST: 0.0.0.0
      MCP_PORT: "8000"
    restart: unless-stopped
    networks:
      - mcpnet

  mcpo:
    image: ghcr.io/open-webui/mcpo:latest
    depends_on:
      - mcp-tavily
    command: >
      mcpo --host 0.0.0.0 --port 8001
           --server-type streamablehttp --
           http://mcp-tavily:8000/mcp
    restart: unless-stopped
    networks:
      - mcpnet

  nginx-auth:
    image: nginx:alpine
    depends_on:
      - mcpo
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    volumes:
      # Mount the single config file directly as a template.
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    command: |
      /bin/sh -c '
        # This is the most direct way: Process our template into the final config location.
        export AUTH_TOKEN && envsubst ''$$AUTH_TOKEN'' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf &&
        
        # Validate and start
        nginx -t && nginx -g "daemon off;"
      '
    ports:
      - "18000:18000"
    restart: unless-stopped
    networks:
      - mcpnet

networks:
  mcpnet:
    driver: bridge