version: '3.8'

services:
  mcp-tavily:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mcp-tavily-search
    restart: unless-stopped
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - MCP_HOST=0.0.0.0
      - MCP_PORT=7000
    networks: 
      - mcp-network
    expose:
      - "7000"
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.post('http://localhost:7000/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    container_name: mcp-tavily-proxy
    restart: unless-stopped
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --server-type
      - streamable-http
      - --
      - http://mcp-tavily-search:7000
    ports:
      - "${EXTERNAL_PORT:-18000}:8000"
    depends_on:
      mcp-tavily:
        condition: service_healthy
    networks: 
      - mcp-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/docs || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  mcp-network:
    driver: bridge