version: "3.8"

services:
  mcp-tavily:
    build:
      context: .
    image: mcp-tavily:latest
    environment:
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      MCP_HOST: 0.0.0.0
      MCP_PORT: "8000"
    restart: unless-stopped
    networks:
      - mcpnet

  mcpo:
    image: ghcr.io/open-webui/mcpo:latest
    depends_on:
      - mcp-tavily
    command: >
      mcpo --host 0.0.0.0 --port 8001
           --server-type streamablehttp --
           http://mcp-tavily:8000
    restart: unless-stopped
    networks:
      - mcpnet

  nginx-auth:
    image: nginx:alpine
    depends_on:
      - mcpo
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}   # set in Portainer env vars (don't commit)
    ports:
      - "18000:18000"
    command: |
      /bin/sh -c '
        set -eu
        cat > /tmp/default.conf.template << "EOF"
        server {
            listen 0.0.0.0:18000;
            resolver 127.0.0.11 ipv6=off valid=10s;
            location / {
                if ($$http_authorization != "Bearer ${AUTH_TOKEN}") { return 401; }
                proxy_pass http://mcpo:8001;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
                proxy_set_header Host $$host;
                proxy_set_header X-Real-IP $$remote_addr;
            }
        }
        EOF
        mkdir -p /etc/nginx/conf.d
        # IMPORTANT: double-$ to keep nginx vars; only $AUTH_TOKEN is substituted
        envsubst "$$AUTH_TOKEN" < /tmp/default.conf.template > /etc/nginx/conf.d/default.conf
        exec nginx -g "daemon off;"
      '
    restart: unless-stopped
    networks:
      - mcpnet

networks:
  mcpnet:
    driver: bridge