services:
  mcp-tavily:
    build: .
    container_name: mcp-tavily
    restart: unless-stopped
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY:-}
    networks: [mcp-network]
    expose:
      - "7000"

  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    container_name: mcpo
    restart: unless-stopped
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --api-key
      - ${MCPO_API_KEY:-supersecret}
      - --server-type
      - streamable-http
      - --
      - http://mcp-tavily:7000/mcp
    ports:
      - "18000:8000"
    depends_on:
      - mcp-tavily
    networks: [mcp-network]
    environment:
      - MCPO_API_KEY=${MCPO_API_KEY:-supersecret}

networks:
  mcp-network:
    driver: bridge