version: "3.9"

services:
  mcp-tavily:
    build: .
    container_name: mcp-tavily
    restart: unless-stopped
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    networks: [owui-mcp]

  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    container_name: mcpo
    restart: unless-stopped
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --api-key
      - supersecret
      - --server-type
      - streamable-http
      - --
      - http://mcp-tavily:7000/mcp
    ports:
      - "18000:8000"      # Open WebUI will hit http://<host>:18000
    depends_on:
      - mcp-tavily
    networks: [owui-mcp]

networks:
  owui-mcp:
    driver: bridge