# MCP Tavily WebSearch - Portainer Stack Configuration
# Deploy this via Portainer Stacks with the environment variables below

services:
  mcp-tavily:
    image: ${STACK_NAME:-mcp-tavily}:latest
    container_name: ${STACK_NAME:-mcp-tavily}-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    networks: 
      - mcp-network
    expose:
      - "7000"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:7000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    container_name: ${STACK_NAME:-mcp-tavily}-proxy
    restart: unless-stopped
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --api-key
      - ${MCPO_API_KEY:-supersecret}
      - --server-type
      - streamable-http
      - --
      - http://${STACK_NAME:-mcp-tavily}-server:7000/mcp
    ports:
      - "${EXTERNAL_PORT:-18000}:8000"
    depends_on:
      mcp-tavily:
        condition: service_healthy
    networks: 
      - mcp-network
    environment:
      - MCPO_API_KEY=${MCPO_API_KEY:-supersecret}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mcp-network:
    driver: bridge
    name: ${STACK_NAME:-mcp-tavily}_network
